### ISSUE TITLE
Outline Quality Checklist

### ISSUE THREAD

**Issue by vv-monsalve** [Vectro-Type-Foundry/kablammo#38]
# Outline Quality Checklist

Make sure your font is ready for mastering by fulfilling this checklist. Design is not particularly judged here, we are talking from the point of view of the technical quality aspect of a font, i.e: what you see in your font editor is what will everyone see on their own screen or printed matter.

### Segments

- [ ] **Mixed outline type :** the outlines of one font must be either PostScript (OpenType Fonts font with CFF compression / .otf) or TrueType (OpenType Fonts with TrueType compression / .ttf). Some editors allow mixed curve type within the same glyph. Whatever the chosen outlines, make sure it is consistent across the entire family.

- [ ] **Wrong direction:** For PS outlines, the outer-shape goes counter-clockwise, and the inner-shape (or counter-shape) goes clockwise. It is the reverse for TT outlines: outer-shape goes clockwise and counter-shape goes counter-clockwise. We usually use PS curves for design, and they are then converted to TT when exporting TTF fonts

- [ ] **Almost straight:** if a segment is misaligned of one or two units, it may be a mistake. This small offset can cause a big misinterpretation from the rasterizer at small ppm sizes.

- [ ] **Missing inflexion point:** It is considered that a curve has a *suspicious inflexion* when it is a single segment going from convex to concave (and vice versa). We need to divide this segment by adding a node at the point where the curve is changing condition, therefore the tangent represented by the two handles crosses the curve.

- [ ] **Collinear:** If two line-segments are connected with the same angle (or almost the same angle), or with a slight offset, it means that the entire line could be made with one segment (two points not more).

- [ ] **Short:** Segments of 1 or 2 units are often used to make ink traps, but they are also sometimes unwanted and, again, can be wildly rendered on some screens.

- [ ] **Open:** A contour can only be considered as such if it has a closed path, otherwise, it won't be rendered at all.

- [ ] **Overlaying:** Ensure there are no overlayed paths, it disturbs rendering, interpolation and variation.

- [ ] **Overlapping:** The crossing of two independent contours is not such a problem in VF (although small overlaps are preferred) and generally merged during the generation of static binaries. If you want to control the result of the merging, it is better to do it yourself. If not, try to keep them in a small overlapped area. Also try to not overlap more than 2 contours in the same area (contour crossing a contour itself crossing another contour, like asterisk, creates confusion during generation and rendering). In any case, try to avoid overlapping shapes which cross a plain shape and a closed counter-shape (typically, Oslash should be manually merged for example).

- [ ] **Self-crossing:** Often known as open-corners, it is very helpful while designing and recommended for nice interpolations. They will be preserved for VF fonts and merged during generation to static binaries. If you want to control the result of the merging, do it yourself if not, same advises as above.

### On-curve points (nodes)

- [ ] **Overlaying:** Also called "empty segments” because they don't have a length. They are often useless and sometimes confusing for hinting and rendering — except for some rare cases of variations.

- [ ] **Missing on extremes:** Required for hinting reasons since they attach hints to the extremum of the stem. Also, having nodes in both in x and y extremes points of the paths will control better the curves and probably reduce the necessity of extra nodes.

- [ ] **Broken smooth connection:** Ensure the right type of node according to the connection, smooth (between to curve segments) or sharp (between a curve and a line segment; or two line segments)

### Off-curve points (handles)

- [ ] **Inside node:** Sometimes ha handle could be present but "hidden" inside of a node and thus disturb rendering, interpolation and variation.
