### ISSUE TITLE
Kablammo To-Do list for publishing into GF

### ISSUE THREAD

**Issue by vv-monsalve** [Vectro-Type-Foundry/kablammo#60]
Hi @traviskochel,

This would be the To-Do list of what should be covered for the publishing process to GF

- [x] Include `name table ID0` [copyright](https://github.com/googlefonts/gf-docs/tree/main/Spec#font-copyright) notice for the font.
- [x] Set fsType to bit 0 "Installable".
- [x] Include Designer and manufacturer's information in the font info.
- [x] Include `name table ID13` License Description, and `name table ID14` License Info URL
- [ ] Review the [Outline Quality Checklist](https://github.com/scribbletone/kablammo/issues/38) and ensure everything is working well for Kablammo.
- [x] Review and solve the [reported Fails](https://github.com/scribbletone/kablammo/issues/59).
- [x] Include the information files in the [repository](https://github.com/googlefonts/gf-docs/tree/main/Spec#upstream-repo-structure): AUTHORS.txt, CONTRIBUTORS.txt, DESCRIPTION.en_us.html plus OFL.txt.
- [ ] Resolve the [Axis Definition](https://github.com/scribbletone/kablammo/issues/28). This should be reviewed again with @davelab6  when all the above is covered.
